name: high-mem-hpc
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - abyss=2.0.2=h51208dd_5
  - asn1crypto=1.4.0=py_0
  - backports=1.0=pyhd3eb1b0_2
  - backports.functools_lru_cache=1.6.1=pyhd3eb1b0_0
  - backports_abc=0.5=py_1
  - bamm=1.7.3=0
  - beagle-lib=3.1.2=hc9558a2_2
  - beast=1.10.4=1
  - bedtools=2.30.0=hc088bd4_0
  - bioawk=1.0=hed695b0_5
  - bioconductor-biobase=2.32.0=0
  - bioconductor-biocgenerics=0.18.0=r3.2.2_0
  - bioconductor-biocparallel=1.4.3=r3.2.2_0
  - bioconductor-biostrings=2.38.4=0
  - bioconductor-dada2=1.0.3=0
  - bioconductor-genomeinfodb=1.6.3=0
  - bioconductor-genomicalignments=1.6.3=1
  - bioconductor-genomicranges=1.22.4=0
  - bioconductor-iranges=2.4.8=0
  - bioconductor-rsamtools=1.22.0=r3.2.2_1
  - bioconductor-s4vectors=0.8.11=0
  - bioconductor-shortread=1.28.0=r3.2.2_0
  - bioconductor-summarizedexperiment=1.0.2=1
  - bioconductor-xvector=0.10.0=1
  - bioconductor-zlibbioc=1.16.0=r3.2.2_1
  - biopython=1.68=py27_0
  - blas=1.0=openblas
  - blast=2.10.1=pl526he19e7b1_3
  - blat=36=0
  - bowtie=1.2.0=py27_0
  - bowtie2=2.2.5=py27h6bb024c_5
  - bwa=0.7.12=1
  - bwa-mem2=2.1=he513fc3_0
  - bz2file=0.98=py27_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.1.19=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - canu=1.4=1
  - cd-hit=4.8.1=hdbcaa40_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.13.2=py27h2e261b9_0
  - chardet=3.0.4=py27_1003
  - circos=0.69.8=0
  - circos-tools=0.23=2
  - clustalw=2.1=hc9558a2_5
  - collectl=4.0.4=2
  - cryptography=2.8=py27h1ba5d50_0
  - curl=7.71.1=hbc83047_1
  - cutadapt=1.18=py27h14c3975_1
  - cycler=0.10.0=py27_0
  - cython=0.27.3=py27hc56b35e_0
  - dbus=1.13.18=hb2f20db_0
  - dendropy=4.5.2=pyh3252c3a_0
  - entrez-direct=13.9=pl526h375a9b1_1
  - enum34=1.1.6=py27_1
  - expat=2.2.10=he6710b0_2
  - fastool=0.1.4=hed695b0_4
  - fastp=0.20.1=h8b12597_0
  - fastq-tools=0.8.3=hed695b0_0
  - fastqc=0.11.9=0
  - fasttree=2.1.10=h516909a_4
  - fastx_toolkit=0.0.14=2
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - functools32=3.2.3.2=py27_1
  - future=0.18.2=py27_0
  - futures=3.3.0=py27_0
  - gatk=3.8=py27_0
  - gatk4=4.1.9.0=py39_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.63.1=h5a9c865_0
  - gnuplot=5.0.3=4
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gsl=2.2.1=h0c605f7_3
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hmmer=3.3.2=he1b5a44_0
  - htslib=1.11=hd3b49d5_2
  - hyphy=2.5.8=ha076c6e_1
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - ipaddress=1.0.23=py_0
  - iqtree=2.0.3=h176a8bc_1
  - java-jdk=8.0.92=1
  - jellyfish=2.2.10=h6bb024c_1
  - jemalloc=4.5.0=0
  - jpeg=9b=h024ee3a_2
  - k8=0.2.5=he513fc3_0
  - kiwisolver=1.1.0=py27he6710b0_0
  - kmergenie=1.7016=py27r3.2.2_0
  - krb5=1.18.2=h173b8e3_0
  - lastz=1.0.4=h516909a_4
  - lca=0.21=he513fc3_0
  - libcurl=7.71.1=h20c2e04_1
  - libdb=6.1.26=0
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgd=2.2.5=h0db58fd_3
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgtextutils=0.7=he1b5a44_6
  - libidn11=1.33=h7b6447c_0
  - libopenblas=0.2.20=h9ac9557_7
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libtool=2.4.6=h7b6447c_1005
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libxslt=1.1.34=hc22bd24_0
  - lxml=4.4.2=py27hefd8a0e_0
  - lz4-c=1.9.3=h2531618_0
  - mafft=7.475=h516909a_0
  - make=4.2.1=h1bed415_1
  - mapdamage2=2.0.6=1
  - matplotlib=2.2.3=py27hb69df0a_0
  - mcl=14.137=pl526h516909a_5
  - megahit=1.2.9=h8b12597_0
  - minimap2=2.17=hed695b0_3
  - mira=4.9.6=1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py27he904b0f_0
  - mmtf-python=1.0.2=py27_0
  - mpi=1.0=openmpi
  - msgpack-python=0.6.1=py27hfd86e86_1
  - muscle=3.8.1551=hc9558a2_5
  - ncurses=6.2=he6710b0_1
  - nose=1.3.7=py27_2
  - novoplasty=4.2=pl526_0
  - numpy=1.14.2=py27_nomklh2b20989_1
  - olefile=0.46=py27_0
  - openblas=0.2.20=7
  - openblas-devel=0.2.20=7
  - openjdk=8.0.152=h7b6447c_3
  - openmpi=4.0.2=hb1b8bf9_1
  - openssl=1.1.1j=h27cfd23_0
  - paml=4.9=h516909a_5
  - pandas=0.24.2=py27he6710b0_0
  - pandoc=2.11=hb0f4dca_0
  - pango=1.42.4=h049681c_0
  - parafly=r2013_01_21=1
  - pasta=1.7.8=py27h14c3975_3
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - perl-aceperl=1.92=pl526_2
  - perl-algorithm-diff=1.1903=pl526_2
  - perl-algorithm-munkres=0.08=pl526_1
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-appconfig=1.71=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-array-compare=3.0.1=pl526_1
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-bio-asn1-entrezgene=1.73=pl526_1
  - perl-bio-coordinate=1.007001=pl526_1
  - perl-bio-featureio=1.6.905=pl526_2
  - perl-bio-phylo=0.58=pl526_2
  - perl-bio-samtools=1.43=pl526h1341992_1
  - perl-bio-tools-phylo-paml=1.7.3=pl526_1
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl526_1
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl526_2
  - perl-bioperl=1.7.2=pl526_11
  - perl-bioperl-core=1.007002=pl526_2
  - perl-bioperl-run=1.007002=pl526_4
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-cache-cache=1.08=pl526_0
  - perl-capture-tiny=0.48=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h14c3975_1
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-inspector=1.34=pl526_0
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h6bb024c_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-constant=1.33=pl526_1
  - perl-convert-binary-c=0.78=pl526h6bb024c_3
  - perl-convert-binhex=1.125=pl526_1
  - perl-cpan-meta=2.150010=pl526_0
  - perl-cpan-meta-requirements=2.140=pl526_0
  - perl-cpan-meta-yaml=0.018=pl526_0
  - perl-crypt-rc4=2.02=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-data-stag=0.14=pl526_1
  - perl-date-format=2.30=pl526_2
  - perl-db-file=1.852=pl526h14c3975_0
  - perl-dbd-sqlite=1.64=pl526h516909a_0
  - perl-dbi=1.642=pl526_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-digest-sha1=2.13=pl526h6bb024c_1
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-dynaloader=1.25=pl526_1
  - perl-email-date-format=1.005=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-error=0.17027=pl526_1
  - perl-eval-closure=0.14=pl526h6bb024c_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-cbuilder=0.280230=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-extutils-manifest=1.72=pl526_0
  - perl-extutils-parsexs=3.35=pl526_0
  - perl-file-find-rule=0.34=pl526_5
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-slurp-tiny=0.004=pl526_1
  - perl-file-sort=1.01=pl526_2
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-filesys-df=0.92=pl526h14c3975_3
  - perl-findbin=1.51=pl526_2
  - perl-font-afm=1.20=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-getopt-long=2.50=pl526_1
  - perl-graph=0.9704=pl526_1
  - perl-graphics-colornames=2.11=pl526_0
  - perl-graphics-colorobject=0.5.0=pl526_1
  - perl-graphviz=2.24=pl526h734ff71_0
  - perl-html-element-extended=1.18=pl526_1
  - perl-html-entities-numbered=0.04=pl526_1
  - perl-html-formatter=2.16=pl526_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tableextract=2.13=pl526_2
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tidy=1.60=pl526_0
  - perl-html-tree=5.07=pl526_1
  - perl-html-treebuilder-xpath=0.14=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-image-info=1.38=pl526_1
  - perl-image-size=3.300=pl526_2
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-sessiondata=1.03=pl526_1
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-stringy=2.111=pl526_1
  - perl-io-tty=1.12=pl526_1
  - perl-io-zlib=1.10=pl526_2
  - perl-ipc-cmd=1.02=pl526_0
  - perl-ipc-run=20180523.0=pl526_0
  - perl-ipc-sharelite=0.17=pl526h6bb024c_1
  - perl-jcode=2.07=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-pp=4.04=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-lib=0.63=pl526_1
  - perl-libwww-perl=6.39=pl526_0
  - perl-libxml-perl=0.08=pl526_2
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-locale-maketext-simple=0.21=pl526_2
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-lwp-simple=6.15=pl526h470a237_4
  - perl-mailtools=2.21=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-cdf=0.1=pl526h14c3975_5
  - perl-math-derivative=1.01=pl526_0
  - perl-math-random=0.72=pl526h14c3975_2
  - perl-math-round=0.07=pl526_1
  - perl-math-spline=0.02=pl526_2
  - perl-math-vecstat=0.08=pl526_1
  - perl-memoize=1.03=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-mime-lite=3.030=pl526_1
  - perl-mime-tools=5.508=pl526_1
  - perl-mime-types=2.17=pl526_0
  - perl-mldbm=2.05=pl526_1
  - perl-module-build=0.4224=pl526_3
  - perl-module-corelist=5.20190524=pl526_0
  - perl-module-implementation=0.09=pl526_2
  - perl-module-load=0.32=pl526_1
  - perl-module-load-conditional=0.68=pl526_2
  - perl-module-loaded=0.08=pl526_0
  - perl-module-metadata=1.000036=pl526_0
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.003004=pl526_0
  - perl-moose=2.2011=pl526hf484d3e_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-mro-compat=0.13=pl526_0
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-compare=0.03=pl526_2
  - perl-number-format=1.75=pl526_3
  - perl-ole-storage_lite=0.19=pl526_3
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526hf484d3e_1
  - perl-package-stash-xs=0.28=pl526hf484d3e_1
  - perl-params-check=0.38=pl526_1
  - perl-params-util=1.07=pl526h6bb024c_4
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-parent=0.236=pl526_1
  - perl-parse-recdescent=1.967015=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-pdf-api2=2.035=pl526_0
  - perl-perl-ostype=1.010=pl526_1
  - perl-pod-escapes=1.07=pl526_1
  - perl-pod-usage=1.69=pl526_1
  - perl-postscript=0.06=pl526_2
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-set-scalar=1.29=pl526_2
  - perl-soap-lite=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-sort-naturally=1.03=pl526_2
  - perl-spreadsheet-parseexcel=0.65=pl526_2
  - perl-spreadsheet-writeexcel=2.40=pl526_2
  - perl-statistics-basic=1.6611=pl526_2
  - perl-statistics-descriptive=3.0702=pl526_0
  - perl-storable=3.15=pl526h14c3975_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h14c3975_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-quote=2.006003=pl526_1
  - perl-sub-uplevel=0.2800=pl526h14c3975_2
  - perl-svg=2.84=pl526_0
  - perl-svg-graph=0.02=pl526_3
  - perl-task-weaken=1.06=pl526_0
  - perl-template-toolkit=2.26=pl526_1
  - perl-test=1.26=pl526_1
  - perl-test-deep=1.128=pl526_1
  - perl-test-differences=0.67=pl526_0
  - perl-test-exception=0.43=pl526_2
  - perl-test-harness=3.42=pl526_0
  - perl-test-leaktrace=0.16=pl526h14c3975_2
  - perl-test-most=0.35=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-test-warn=0.36=pl526_1
  - perl-text-abbrev=1.02=pl526_0
  - perl-text-diff=1.45=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-text-glob=0.11=pl526_1
  - perl-text-parsewords=3.30=pl526_0
  - perl-threaded=5.26.0=0
  - perl-tie-ixhash=1.23=pl526_2
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-time-local=1.28=pl526_1
  - perl-timedate=2.30=pl526_1
  - perl-tree-dag_node=1.31=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-type-tiny=1.004004=pl526_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-unicode-map=0.112=pl526h6bb024c_3
  - perl-uri=1.76=pl526_0
  - perl-version=0.9924=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-dom=1.46=pl526_0
  - perl-xml-dom-xpath=0.14=pl526_1
  - perl-xml-filter-buffertext=1.01=pl526_2
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-libxslt=1.94=pl526_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44=pl526h4e0c4b3_7
  - perl-xml-regexp=0.04=pl526_2
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-sax-writer=0.57=pl526_0
  - perl-xml-simple=2.25=pl526_1
  - perl-xml-twig=3.52=pl526_2
  - perl-xml-writer=0.625=pl526_2
  - perl-xml-xpath=1.44=pl526_0
  - perl-xml-xpathengine=0.14=pl526_2
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - phylip=3.697=h470a237_0
  - phyml=3.3.20190909=h516909a_0
  - picard=2.25.0=0
  - pigz=2.4=h84994c4_0
  - pillow=6.2.1=py27h34e0f95_0
  - pip=19.3.1=py27_0
  - pixman=0.40.0=h7b6447c_0
  - plink=1.90b6.18=h516909a_0
  - plink2=2.00a2.3=hf22980b_0
  - pplacer=1.1.alpha19=1
  - prank=v.170427=hc9558a2_3
  - prinseq=0.20.4=4
  - pycparser=2.20=py_2
  - pymongo=3.9.0=py27he6710b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py27h05f1152_2
  - pysam=0.8.4=py27_0
  - pysocks=1.7.1=py27_0
  - python=2.7.18=h02575d3_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - r=3.2.2=0
  - r-assertthat=0.1=r3.2.2_1a
  - r-base=3.2.2=0
  - r-base64enc=0.1_3=r3.2.2_0a
  - r-bh=1.60.0_2=r3.2.2_0
  - r-bitops=1.0_6=r3.2.2_1a
  - r-boot=1.3_17=r3.2.2_0a
  - r-car=2.1_0=r3.2.2_0a
  - r-caret=6.0_62=r3.2.2_0a
  - r-catools=1.17.1=r3.2.2_0
  - r-chron=2.3_47=r3.2.2_0a
  - r-class=7.3_14=r3.2.2_0a
  - r-cluster=2.0.3=r3.2.2_0a
  - r-codetools=0.2_14=r3.2.2_0a
  - r-colorspace=1.2_6=r3.2.2_0a
  - r-data.table=1.9.6=r3.2.2_0a
  - r-dbi=0.3.1=r3.2.2_2a
  - r-dichromat=2.0_0=r3.2.2_2a
  - r-digest=0.6.9=r3.2.2_0
  - r-dplyr=0.4.3=r3.2.2_0a
  - r-essentials=1.1=r3.2.2_0a
  - r-evaluate=0.8=r3.2.2_0a
  - r-foreach=1.4.3=r3.2.2_0a
  - r-foreign=0.8_66=r3.2.2_0a
  - r-formatr=1.2.1=r3.2.2_0a
  - r-futile.logger=1.4.1=r3.2.2_0
  - r-futile.options=1.0.0=r3.2.2_0
  - r-ggplot2=2.1.0=r3.2.2_0
  - r-glmnet=2.0_2=r3.2.2_0a
  - r-gtable=0.1.2=r3.2.2_2a
  - r-hexbin=1.27.1=r3.2.2_0a
  - r-highr=0.5.1=r3.2.2_0a
  - r-htmltools=0.3=r3.2.2_0
  - r-htmlwidgets=0.5=r3.2.2_0a
  - r-httpuv=1.3.3=r3.2.2_0a
  - r-hwriter=1.3.2=r3.2.2_0
  - r-irdisplay=0.3=r3.2.2_0a
  - r-irkernel=0.5=r3.2.2_2
  - r-iterators=1.0.8=r3.2.2_0a
  - r-jsonlite=0.9.19=r3.2.2_0
  - r-kernsmooth=2.23_15=r3.2.2_0a
  - r-knitr=1.11=r3.2.2_0a
  - r-labeling=0.3=r3.2.2_1a
  - r-lambda.r=1.1.7=r3.2.2_0
  - r-lattice=0.20_33=r3.2.2_0a
  - r-latticeextra=0.6_26=r3.2.2_2a
  - r-lazyeval=0.1.10=r3.2.2_2a
  - r-lme4=1.1_10=r3.2.2_0a
  - r-magrittr=1.5=r3.2.2_0
  - r-maps=3.0.0_2=r3.2.2_0a
  - r-markdown=0.7.7=r3.2.2_1a
  - r-mass=7.3_45=r3.2.2_0a
  - r-matrix=1.2_2=r3.2.2_0a
  - r-matrixmodels=0.4_1=r3.2.2_0a
  - r-mgcv=1.8_9=r3.2.2_0a
  - r-mime=0.4=r3.2.2_0a
  - r-minqa=1.2.4=r3.2.2_1a
  - r-munsell=0.4.2=r3.2.2_1a
  - r-nlme=3.1_122=r3.2.2_0a
  - r-nloptr=1.0.4=r3.2.2_1a
  - r-nnet=7.3_11=r3.2.2_0a
  - r-pbkrtest=0.4_2=r3.2.2_2a
  - r-plyr=1.8.3=r3.2.2_0a
  - r-quantmod=0.4_5=r3.2.2_0a
  - r-quantreg=5.19=r3.2.2_0a
  - r-r6=2.1.1=r3.2.2_0a
  - r-randomforest=4.6_12=r3.2.2_0a
  - r-rbokeh=0.2.2=r3.2.2_0a
  - r-rcolorbrewer=1.1_2=r3.2.2_2a
  - r-rcpp=0.12.2=r3.2.2_0a
  - r-rcppeigen=0.3.2.5.1=r3.2.2_0a
  - r-recommended=3.2.2=r3.2.2_0
  - r-repr=0.3=r3.2.2_0a
  - r-reshape2=1.4.1=r3.2.2_1a
  - r-rjsonio=1.3_0=r3.2.2_1a
  - r-rmarkdown=0.8.1=r3.2.2_0a
  - r-rpart=4.1_10=r3.2.2_0a
  - r-rzmq=0.7.7=r3.2.2_3a
  - r-scales=0.3.0=r3.2.2_0a
  - r-shiny=0.12.2=r3.2.2_0a
  - r-snow=0.4_1=r3.2.2_0
  - r-sparsem=1.7=r3.2.2_0a
  - r-spatial=7.3_11=r3.2.2_0a
  - r-stringi=1.0_1=r3.2.2_0a
  - r-stringr=1.0.0=r3.2.2_0a
  - r-survival=2.38_3=r3.2.2_0a
  - r-tidyr=0.3.1=r3.2.2_0a
  - r-ttr=0.23_0=r3.2.2_0a
  - r-uuid=0.1_2=r3.2.2_0a
  - r-xtable=1.8_0=r3.2.2_0a
  - r-xts=0.9_7=r3.2.2_0a
  - r-yaml=2.1.13=r3.2.2_0
  - r-zoo=1.7_12=r3.2.2_1a
  - racon=1.4.20=he513fc3_0
  - raxml=8.2.12=h516909a_2
  - readline=8.1=h27cfd23_0
  - regex=2016.06.24=py27_1
  - reportlab=3.5.26=py27he686d34_0
  - requests=2.25.1=pyhd3eb1b0_0
  - samtools=1.2=2
  - scipy=1.1.0=py27_nomklh9c1e066_0
  - seqtk=1.3=hed695b0_2
  - setuptools=44.0.0=py27_0
  - sickle=0.7.0=pyh9f0ad1d_0
  - singledispatch=3.4.0.3=py_1001
  - sip=4.19.8=py27hf484d3e_0
  - six=1.15.0=pyhd3eb1b0_0
  - slclust=02022010=2
  - snpeff=5.0=0
  - spades=3.13.0=0
  - sqlite=3.33.0=h62c20be_0
  - sra-tools=2.8.0=0
  - structure=2.3.4=h516909a_2
  - subprocess32=3.5.4=py27h7b6447c_0
  - t_coffee=11.0.8=py27hea885bf_8
  - tbb=2020.3=hfd86e86_0
  - tbl2asn=25.7=0
  - tidyp=1.04=h516909a_2
  - tk=8.6.10=hbc83047_0
  - tophat=2.1.1=py27_3
  - tornado=5.1.1=py27h7b6447c_0
  - translatorx=1.1=2
  - trimal=1.4.1=hc9558a2_4
  - trimmomatic=0.39=1
  - trinity=2.1.1=6
  - trinotate=3.2.1=pl526_0
  - umi_tools=0.5.4=py27h470a237_2
  - urllib3=1.25.7=py27_0
  - varscan=2.4.4=0
  - vcftools=0.1.16=he513fc3_4
  - vsearch=2.15.2=h2d02072_0
  - wget=1.20.1=h20c2e04_0
  - wgs2ncbi=1.1.2=pl526_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xopen=0.7.3=py_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - faststructure==0.0.0
prefix: /home/ubuntu/miniconda3/envs/high-mem-hpc
