name: high-mem-hpc
channels:
  - bioconda
dependencies:
  - samtools
  - bwa
  - minimap2
  - bcftools
  - raxml
  - bamm
  - beast
  - bioawk
  - perl-bioperl
  - phylip
  - cutadapt
  - fastp
  - fastqc
  - spades
  - fastq-tools
  - kmergenie
  - muscle
  - nanofilt
  
# exabayes
# partitionfinder
